version: '3'
services:
  nodejs-server:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    container_name: backend-martingoals
    volumes:
       - ./backend/src
  react-ui:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    container_name: frontend-martingoals
    stdin_open: true
    volumes:
       - ./frontend/src